---
title: "2nd_week_assignment"
output: html_document
date: '2022-03-03'
---

# practice using apply() function.

## for the numeric matrix
```{r}

## function for the numeric matrix
sum_posneg_a <- function(matrix, dir) {
	mat1 <- matrix(nrow = nrow(matrix), ncol = 2)
	mat2 <- matrix(nrow = 2, ncol = ncol(matrix))
	# sum of (positive value, negative value) on each row
	if (dir == 1)
	{
		for (i in 1 : nrow(matrix))
		{
			mat1[i, 1] = sum(matrix[i, matrix[i, ] >= 0])
			mat1[i, 2] = sum(matrix[i, matrix[i, ] < 0])
		}
		return (mat1)
	}
	# sum of (positive value, negative value) on each column
	else if (dir == 2) {
		for (i in 1 : ncol(matrix))
		{
			mat2[1, i] = sum(matrix[matrix[, i] >= 0, i])
			mat2[2, i] = sum(matrix[matrix[, i] < 0, i])
		}
		return (mat2)
	}
	## error message : when dir is neither 1 nor 2
	else
	{
		print("[error] invalid direction value.")
	}
	return (matrix)
}

## function for the numeric matrix
sum_posneg_b <- function(matrix, dir)
{
	if (dir != 1 && dir != 2) {
		print("[error] invalid direction value.")
		return (matrix)
	}
	mat_pos <- matrix
	mat_neg <- matrix
	# Try NA masking to filter each positive/negative value in given matrix.
	mat_pos[matrix < 0] <- NA
	mat_neg[matrix >= 0] <- NA
	# make sum of each positive/negative vector of each row/column
	pm = apply(mat_pos, dir, sum, na.rm=TRUE)
	nm = apply(mat_neg, dir, sum, na.rm=TRUE)
	# bind positive & negative sum vector to make matrix
	if (dir == 1)
		return (cbind(pm, nm))
	else
	{
		return (rbind(pm, nm))
	}
}

# ==========================================================================

## set matrix
mat <- matrix(data = c(1, -1, 1, -1, 1, 1, -2, 1, 1), nrow = 3, ncol = 3)

## display matrix
cat("============== ORIGINAL MATRIX ===============\n\n")
print(mat)
cat("==============================================\n")

## get return value from made function
cat("sum_posneg_a(matrix, dir = 1)\n\n")
result <- sum_posneg_a(mat, 1)
print(result)
cat("----------------------------------------------\n")
cat("sum_posneg_a(matrix, dir = 2)\n\n")
result <- sum_posneg_a(mat, 2)
print(result)

cat("==============================================\n")
cat("sum_posneg_b(matrix, dir = 1)\n\n")
result <- sum_posneg_b(mat, 1)
print(result)
cat("----------------------------------------------\n")
cat("sum_posneg_b(matrix, dir = 2)\n\n")
result <- sum_posneg_b(mat, 2)
print(result)

```

## for the character matrix 
```{r}
## function definition
count_substr_a <- function(matrix, str, dir) {
	res <- c()
	if (dir == 1)
	{
		for (i in 1 : nrow(matrix))
		{
			row <- grepl(str, matrix[i, ]) 
			# get vector of TRUE/FALSE. TRUE means it contains target substring inside.
			res <- rbind(res, length(row[row == TRUE])) 
			# count TRUE elements and add those element to the bottom of the row.
 		}
	}
	else if (dir == 2) {
		for (i in 1 : ncol(matrix))
		{
			col <- grepl(str, matrix[, i])
			# get vector of TRUE/FALSE. TRUE means it contains target substring inside.
			res <- cbind(res, length(col[col == TRUE]))
			# count TRUE elements and add those element to the right edge of the column.
 		}
	}
	else {
		print("[error] invalid direction value.")
	}
	return (res)
}

## function definition
count_substr_b <- function(matrix, str, dir) {
	# exception handling
	if (dir != 1 && dir != 2) { 
		print("[error] invalid direction value.")
		return (NULL)
	}
	# use stringr library
	library(stringr)
	tmp <- apply(matrix, 2, str_detect, str) 
	# count TRUE in the given direction
	res <- apply(tmp, dir, sum, na.rm = TRUE) 
	# convert vector to a matrix
	if (dir == 1) {
		res <- matrix(data = res, nrow = nrow(matrix), ncol = 1)
	}
	else if (dir == 2) {
		res <- matrix(data = res, nrow = 1, ncol = ncol(matrix))
	}
	return (res)
}

# ==========================================================================

## set matrix
mat <- matrix(data = c('happy', 'hangout', 'hangover', 'what is happiness',
	'what', 'is', 'me', 'That is me', 'That'), nrow = 3, ncol = 3)
str <- c('what')

## display matrix
cat("============== ORIGINAL MATRIX ===============\n\n")
print(mat)
cat("\nsubstring to find :", str[1], "\n\n")
cat("==============================================\n")

## get return value from the function
cat("count_substr_a(matrix, dir = 1)\n\n")
result <- count_substr_a(mat, str, 1)
print(result)
cat("----------------------------------------------\n")
cat("count_substr_a(matrix, dir = 2)\n\n")
result <- count_substr_a(mat, str, 2)
print(result)

cat("==============================================\n")

cat("count_substr_b(matrix, dir = 1)\n\n")
result <- count_substr_b(mat, str, 1)
print(result)
cat("----------------------------------------------\n")
cat("count_substr_b(matrix, dir = 2)\n\n")
result <- count_substr_b(mat, str, 2)
print(result)

```